backend:
  name: github
  repo: mgupt04/farmtotable
  branch: main

media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "messages"
    label: "Messages"
    folder: "content"
    create: true
    fields:
      - { label: "Message", name: "message", widget: "string" }
