backend:
  name: github
  repo: mgupt04/farmtotable
  branch: main


media_folder: "slide1_files"
public_folder: "/images"

collections:
  - name: "messages"
    label: "Messages"
    folder: "slide1_files"
    create: true
    fields:
      - { label: "Message", name: "message", widget: "string" }
